<a href="https://colab.research.google.com/github/prakashkrishanan/Data-science/blob/main/1_task1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

task 1 question 1

a.Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [ ]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

# Update the sixth value to 11
null_vector[5] = 11

print("Null vector with sixth value updated:", null_vector)


Null vector with sixth value updated: [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


b.To convert an array to a float type, you can use the 'astype' method:

In [ ]:
import numpy as np

# Create an integer array
int_array = np.array([1, 2, 3, 4, 5])

# Convert the array to float type
float_array = int_array.astype(float)

print("Original array:", int_array)
print("Array converted to float type:", float_array)


Original array: [1 2 3 4 5]
Array converted to float type: [1. 2. 3. 4. 5.]


c.To create a 3x3 matrix with values ranging from 2 to 10:

In [ ]:
import numpy as np

# Create a 3x3 matrix with values ranging from 2 to 10
matrix = np.arange(2, 11).reshape(3, 3)

print("3x3 Matrix with values ranging from 2 to 10:")
print(matrix)


3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


d.To convert a list of numeric values into a one-dimensional NumPy array:

In [ ]:
import numpy as np

# Create a list of numeric values
numeric_list = [1, 2, 3, 4, 5]

# Convert the list to a one-dimensional NumPy array
numpy_array = np.array(numeric_list)

print("List converted to NumPy array:", numpy_array)


List converted to NumPy array: [1 2 3 4 5]
