<a href="https://colab.research.google.com/github/prakashkrishanan/Data-science/blob/main/4_task1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Write a NumPy program to convert an array to a float type

In [ ]:
import numpy as np

# Creating an integer array
int_array = np.array([1, 2, 3, 4, 5])

# Converting the array to float
float_array = int_array.astype(float)

print("Original Array (Integer):", int_array)
print("Converted Array (Float):", float_array)


Original Array (Integer): [1 2 3 4 5]
Converted Array (Float): [1. 2. 3. 4. 5.]


b. Create an empty and a full array:

In [ ]:
import numpy as np

# Creating an empty array
empty_array = np.empty((3, 3))

# Creating a full array with a specific value
full_array = np.full((2, 4), 7)

print("Empty Array:")
print(empty_array)

print("\nFull Array:")
print(full_array)


Empty Array:
[[4.84290625e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]

Full Array:
[[7 7 7 7]
 [7 7 7 7]]


c. Convert a list and tuple into arrays:

In [ ]:
import numpy as np

# Converting a list to an array
list_data = [1, 2, 3, 4, 5]
array_from_list = np.array(list_data)

# Converting a tuple to an array
tuple_data = (10, 20, 30, 40, 50)
array_from_tuple = np.array(tuple_data)

print("Array from List:", array_from_list)
print("Array from Tuple:", array_from_tuple)


Array from List: [1 2 3 4 5]
Array from Tuple: [10 20 30 40 50]


d. Find the real and imaginary parts of an array of complex numbers:

In [ ]:
import numpy as np

# Creating an array of complex numbers
complex_array = np.array([1 + 2j, 3 - 4j, 5 + 6j])

# Extracting real and imaginary parts
real_parts = np.real(complex_array)
imaginary_parts = np.imag(complex_array)

print("Original Complex Array:", complex_array)
print("Real Parts:", real_parts)
print("Imaginary Parts:", imaginary_parts)


Original Complex Array: [1.+2.j 3.-4.j 5.+6.j]
Real Parts: [1. 3. 5.]
Imaginary Parts: [ 2. -4.  6.]
