<a href="https://colab.research.google.com/github/prakashkrishanan/Data-science/blob/main/6_task_1_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

19.Write a NumPy program to merge three given NumPy arrays of same shape

In [ ]:
import numpy as np

# Creating three NumPy arrays of the same shape
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
array3 = np.array([[13, 14, 15], [16, 17, 18]])

# Merging the arrays along the first axis (axis=0)
merged_array = np.concatenate((array1, array2, array3), axis=0)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nArray 3:")
print(array3)
print("\nMerged Array:")
print(merged_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Array 3:
[[13 14 15]
 [16 17 18]]

Merged Array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
