<a href="https://colab.research.google.com/github/prakashkrishanan/Data-science/blob/main/Task1(Beginners_of_numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#creating arrays
print(np.array([1,2,3,4,5]))#create an simple array
print(np.zeros(10))#create an array of 10 zeros
print(np.ones(10))#create an array of 10 ones
print(np.arange(15))#create an array range of 0 to 14
print(np.linspace(1,5,5))#create an array with evenly spaced numbers over a specified range
print(np.eye(3))#create a identity matrix with given specified value

[1 2 3 4 5]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1. 2. 3. 4. 5.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#array information
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])#indicates the no of rows and columns
print(a.shape)
print(a.ndim)#used to get the number of array dimensions
print(a.size)#returns the total nubers of elements
print(a.dtype)#returns the data type of the elements

(1, 3, 3)
3
9
int64


In [ ]:
#array operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.add(a,b))#element wise addition
print(np.subtract(b,a))#element wise subtraction
print(np.multiply(a,b))#element wise multiplication
print(np.divide(b,a))#element wise divide
print(np.dot(a,b))#returns the dot product value of two array

[5 7 9]
[3 3 3]
[ 4 10 18]
[4.  2.5 2. ]
32


In [ ]:
#array manipulation
a=np.array([1,2,3,4])
print(a.reshape(2,2))#reshaping the array without changing the values
b=np.array([5,6,7,8])
print(np.concatenate([a,b]))#cancatenate the two arrays
print(np.split(a,[2,2]))#splitting the array to desired shape
c=np.array([[1,2,3],[4,5,6]])
print(c.transpose())#transpose the array

[[1 2]
 [3 4]]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([], dtype=int64), array([3, 4])]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#mathemethical functions
import numpy as np
a=np.array([1,3,5])
b=np.array([2,4,6])
print(a+b)
print(sum(a,b))#sum of array elements
print(min(a))#to fint minimum element in array
print(max(a))#to find maximum element in array
print(np.mean(b))#to find mean value of an array
print(np.median(b))#to find median value of an array
print(np.std(a))#to finrd the standard deviation value in array

[ 3  7 11]
[11 13 15]
1
5
4.0
4.0
1.632993161855452


In [ ]:
#trignomentric functions
a=np.array([2,4,5,8,10])
print(np.exp(a))#to find the exponential value of array
print(np.sqrt(a))#to find the sqaure root value of array
print(np.sin(a))#to find the sin value of array
print(np.cos(a))#to find the cosine value of array
print(np.log(a))#to find the logarithm value of array
print(np.tan(a))#to find the tangent value of array

[7.38905610e+00 5.45981500e+01 1.48413159e+02 2.98095799e+03
 2.20264658e+04]
[1.41421356 2.         2.23606798 2.82842712 3.16227766]
[ 0.90929743 -0.7568025  -0.95892427  0.98935825 -0.54402111]
[-0.41614684 -0.65364362  0.28366219 -0.14550003 -0.83907153]
[0.69314718 1.38629436 1.60943791 2.07944154 2.30258509]
[nan nan nan nan nan]


<ipython-input-58-e0229b95df94>:11: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(a))


In [ ]:
#inverse trignometric functions
a=np.array([0,0.5,1])
print(np.arcsin(a))#used to compute the inverse sin
print(np.arccos(a))#used to compute the inverse cos
print(np.arctan(a))#used to compute the inverse tan

[0.         0.52359878 1.57079633]
[1.57079633 1.04719755 0.        ]
[0.         0.46364761 0.78539816]


In [ ]:
#random

a=np.random.rand(2,2)#used to generate random numbers in the intervel between[0,1]
print(a)
b=np.random.randn(2,2)#used to generate random numbers from a standard number distribution
print(b)
c=np.random.randint(1,10,(2,2))#used to print random value from low to high with range
print(c)
d=np.array([3,4,5,6,7])#used to shuffle the array
print(np.random.shuffle(d))

[[0.72527988 0.54570471]
 [0.99709446 0.18450798]]
[[ 0.81130035 -0.29670415]
 [ 0.11516228  1.29716461]]
[[8 5]
 [8 5]]
None


In [ ]:
#statistical functions
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 50th percentile (median)
median = np.percentile(data, 50)
print("Median:", median)

import numpy as np

# Create two arrays for demonstration
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])

# Compute the correlation coefficient matrix
corr_matrix = np.corrcoef(x, y)

print("Correlation coefficient matrix:")
print(corr_matrix)

Median: 5.5
Correlation coefficient matrix:
[[1. 1.]
 [1. 1.]]


In [ ]:
#logical operations
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])
a = np.logical_and(arr1, arr2)#perfors logical and functions
print(a)
b=np.logical_or(arr1,arr2)#performs logical or functions
print(b)
arr1 = np.array([True, True, False, False])
c=np.logical_not(arr1)#performs logical not functions
print(c)

[ True False False False]
[ True  True  True False]
[False False  True  True]


In [ ]:
#linear algebra
import numpy as np

# Create a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Compute the inverse of the matrix
A_inv = np.linalg.inv(A)
print("\nInverse Matrix:")
print(A_inv)



# Create a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Compute the determinant of the matrix
det_A = np.linalg.det(A)
print("\nDeterminant:", det_A)



# Create a 2x2 matrix
A = np.array([[4, 7],
              [2, 6]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Inverse Matrix:
[[ 0.6 -0.7]
 [-0.2  0.4]]

Determinant: 10.000000000000002

Eigenvalues:
[1.12701665 8.87298335]

Eigenvectors:
[[-0.92511345 -0.82071729]
 [ 0.37969079 -0.57133452]]


In [ ]:
#sorting

# Create an unsorted array
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
# Sort the array
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

Sorted array: [1 1 2 3 3 4 5 5 5 6 9]


In [ ]:
#file input\output

# Create an array
arr = np.array([1, 2, 3, 4, 5])
# Save the array to a file
np.save('saved_array.npy', arr)

loaded_arr = np.load('saved_array.npy')
print("Loaded array:", loaded_arr)


Loaded array: [1 2 3 4 5]
