<a href="https://colab.research.google.com/github/prakashkrishanan/Data-science/blob/main/Task4(100_Numpy_task).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises


File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
print(np.show_config())


NumPy Version: 1.23.5
NumPy Configuration:
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language =

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
null_vector = np.zeros(10)#creating null vectors
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np

# Create an example array
my_array = np.zeros((3, 4), dtype=np.int32)

# Find the memory size of the array
memory_size = my_array.nbytes

print(f"Memory size of the array: {memory_size} bytes")




Memory size of the array: 48 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
help(np.add)


Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
my_vector = np.arange(10, 50)
print(my_vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
my_vector = np.arange(10, 50)
reversed_vector = my_vector[::-1]
print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
import numpy as np
print(np.arange(9).reshape(3, 3))


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
import numpy as np
my_array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(my_array)
print(nonzero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
random_array = np.random.random((3, 3, 3))
print(random_array)



[[[0.09842958 0.81069954 0.70163317]
  [0.98112267 0.83470188 0.64459002]
  [0.76299101 0.02693612 0.73688697]]

 [[0.84155449 0.40510784 0.68451351]
  [0.64840118 0.84762888 0.89881809]
  [0.8173619  0.9464569  0.86941883]]

 [[0.2508241  0.26914879 0.32846821]
  [0.05761446 0.14076097 0.61833281]
  [0.25297636 0.68880363 0.84534952]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
import numpy as np
random_array = np.random.random((10, 10))
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.00602563246117882
Maximum value: 0.9560258566274628


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
import numpy as np
random_vector = np.random.random(30)
mean_value = np.mean(random_vector)
print("Random Vector:", random_vector)
print("Mean Value:", mean_value)


Random Vector: [0.13854395 0.126721   0.24343641 0.82750365 0.7540915  0.52170932
 0.68011685 0.10886212 0.61736089 0.9681449  0.67154639 0.81201073
 0.33283217 0.29359004 0.31386231 0.26098013 0.92514049 0.95932438
 0.29850179 0.6920863  0.90938751 0.85365639 0.91805556 0.66249886
 0.95439071 0.75155178 0.7692691  0.31080109 0.94663297 0.25205188]
Mean Value: 0.5958220397807759


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
import numpy as np
rows, cols = 5, 5
my_array = np.zeros((rows, cols), dtype=int)
my_array[0, :] = 1
my_array[-1, :] = 1
my_array[:, 0] = 1
my_array[:, -1] = 1
print(my_array)



[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
existing_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
rows, cols = existing_array.shape
larger_array = np.zeros((rows + 2, cols + 2), dtype=existing_array.dtype)
larger_array[1:-1, 1:-1] = existing_array
print("Existing Array:")
print(existing_array)
print("\nArray with Border:")
print(larger_array)

Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
import numpy as np

result1 = 0 * np.nan
result2 = np.nan == np.nan
result3 = np.inf > np.nan
result4 = np.nan - np.nan
result5 = np.nan in set([np.nan])
result6 = 0.3 == 3 * 0.1
Result1: nan
Result2: False
Result3: False
Result4: nan
Result5: True
Result6: True


NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
import numpy as np
my_matrix = np.diag([1, 2, 3, 4], k=-1)
print(my_matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]




```
# This is formatted as code
```

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:

import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np

shape = (6, 7, 8)
desired_index = 100
indices = np.unravel_index(desired_index, shape)

print(f"The indices (x, y, z) of the 100th element are: {indices}")


The indices (x, y, z) of the 100th element are: (1, 5, 4)


*italicized text*#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
base_checkerboard = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(base_checkerboard, (4, 4))
print(checkerboard)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
import numpy as np
random_matrix = np.random.rand(5, 5)
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)
normalized_matrix = (random_matrix - mean_value) / std_deviation
print("Original Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


[link text](https://)#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])
color_array = np.array([(255, 0, 0, 255),
                       (0, 255, 0, 128)],
                      dtype=color_dtype)
print("First color:", color_array[0])
print("Red channel of the first color:", color_array['red'][0])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
import numpy as np
matrix_A = np.random.rand(5, 3)
matrix_B = np.random.rand(3, 2)
matrix_C = np.dot(matrix_A, matrix_B)
print("Matrix A (5x3):")
print(matrix_A)
print("\nMatrix B (3x2):")
print(matrix_B)
print("\nResulting Matrix C (5x2):")
print(matrix_C)


Matrix A (5x3):
[[0.8584024  0.06557318 0.8831528 ]
 [0.53659043 0.458612   0.58204177]
 [0.81317285 0.11061401 0.52910062]
 [0.21561743 0.49339953 0.53579491]
 [0.8565471  0.48627119 0.8465431 ]]

Matrix B (3x2):
[[0.47306844 0.41799288]
 [0.77361803 0.94297345]
 [0.30784997 0.79226363]]

Resulting Matrix C (5x2):
[[0.72869024 1.1203297 ]
 [0.78781605 1.11788044]
 [0.63314301 0.86339371]
 [0.64864902 0.97988002]
 [1.04200183 1.48725672]]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-4-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-4-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[  2.   8.   6.   9.  -5.  -1.   7.  -3. -10.   9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1)
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-9-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 6. 3. 4. 1. 7. 2. 1. 5. 3.]
[8. 6. 3. 4. 1. 7. 2. 1. 5. 3.]
[8. 6. 3. 4. 1. 7. 2. 1. 5. 3.]
[8 6 3 4 1 7 2 1 5 3]
[8. 6. 3. 4. 1. 7. 2. 1. 5. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,12,endpoint=True)[1:-1]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.00138572 0.08267955 0.14387396 0.16566457 0.23521036 0.33848824
 0.55150152 0.72908906 0.76352848 0.82063865]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
import numpy as np

# Create a small array
arr = np.array([1, 2, 3, 4, 5])

# Using np.sum
result_np = np.sum(arr)
print("np.sum result:", result_np)

# Using built-in sum
result_builtin = sum(arr)
print("Built-in sum result:", result_builtin)


np.sum result: 15
Built-in sum result: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
import numpy as np

# Create two random arrays A and B
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

# Print the result
print("Arrays are equal:", are_equal)


Arrays are equal: False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Make the array read-only
arr.flags.writeable = False

# Try to modify the array (this will raise an error)
# Uncomment the following line to see the error
# arr[0] = 10


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import numpy as np

# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coordinates = np.random.rand(10, 2)

# Extract x and y coordinates
x = cartesian_coordinates[:, 0]
y = cartesian_coordinates[:, 1]

# Convert to polar coordinates
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

# Display the results
print("Cartesian Coordinates:")
print(cartesian_coordinates)
print("\nPolar Coordinates:")
print(np.column_stack((r, theta)))


Cartesian Coordinates:
[[0.29566082 0.08389961]
 [0.57620619 0.65639246]
 [0.10107334 0.61469769]
 [0.17392752 0.25985378]
 [0.25528077 0.66419374]
 [0.54518268 0.01420004]
 [0.92495082 0.24515988]
 [0.68767262 0.88893868]
 [0.27556782 0.49419932]
 [0.52495021 0.2012297 ]]

Polar Coordinates:
[[0.30733445 0.276501  ]
 [0.87342123 0.85036127]
 [0.6229519  1.40782687]
 [0.31268957 0.98095325]
 [0.71156278 1.20385644]
 [0.54536758 0.02604049]
 [0.95688944 0.25909413]
 [1.12387972 0.91236879]
 [0.56583619 1.0621334 ]
 [0.56219758 0.36605451]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Original random vector:")
print(random_vector)


Original random vector:
[0.         0.33282323 0.72379473 0.49537629 0.56127731 0.66607343
 0.2072224  0.44215384 0.50986096 0.44698658]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
import numpy as np

# Define the size of the structured array
array_size = 10

# Create a structured array with x and y coordinates
structured_array = np.zeros(array_size, dtype=[('x', float), ('y', float)])

# Fill in the x and y coordinates with values in the [0, 1] range
structured_array['x'] = np.random.rand(array_size)
structured_array['y'] = np.random.rand(array_size)

print("Structured Array:")
print(structured_array)


Structured Array:
[(0.920667  , 0.5363293 ) (0.28530286, 0.62398739)
 (0.15535074, 0.8573908 ) (0.62802758, 0.00751688)
 (0.50118173, 0.98141028) (0.95193672, 0.05729544)
 (0.2605127 , 0.132381  ) (0.68442288, 0.38508629)
 (0.73249194, 0.04496624) (0.79339172, 0.08923676)]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
import numpy as np

# Example arrays X and Y
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

# Construct the Cauchy matrix C
C = 1.0 / (X[:, np.newaxis] - Y)

print("Cauchy Matrix C:")
print(C)


Cauchy Matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
import numpy as np

# Floating-point types
float_types = [np.float16, np.float32, np.float64]
for dtype in float_types:
    info = np.finfo(dtype)
    print(f"{dtype}: Min = {info.min}, Max = {info.max}")

# Integer types
int_types = [np.int8, np.int16, np.int32, np.int64]
for dtype in int_types:
    info = np.iinfo(dtype)
    print(f"{dtype}: Min = {info.min}, Max = {info.max}")

<class 'numpy.float16'>: Min = -65504.0, Max = 65504.0
<class 'numpy.float32'>: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
<class 'numpy.float64'>: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308
<class 'numpy.int8'>: Min = -128, Max = 127
<class 'numpy.int16'>: Min = -32768, Max = 32767
<class 'numpy.int32'>: Min = -2147483648, Max = 2147483647
<class 'numpy.int64'>: Min = -9223372036854775808, Max = 9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print all values
print("All values of the array:")
print(my_array)


All values of the array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
import numpy as np

# Create a NumPy array
my_array = np.array([1.2, 3.5, 4.8, 7.2, 9.0])

# Given scalar
target_scalar = 5.0

# Find the index of the closest value
closest_index = np.abs(my_array - target_scalar).argmin()

# Get the closest value
closest_value = my_array[closest_index]

print(f"Given array: {my_array}")
print(f"Target scalar: {target_scalar}")
print(f"Closest value: {closest_value} at index {closest_index}")


Given array: [1.2 3.5 4.8 7.2 9. ]
Target scalar: 5.0
Closest value: 4.8 at index 2


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-2-dd3adfbd69b6>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.18290259 0.21113918 0.62164973 0.30210819 0.7498206
  0.6851469  0.45874008 0.56856564 0.35137355]
 [0.18290259 0.         0.06050327 0.48456532 0.12134082 0.58004839
  0.5023576  0.5270641  0.5268862  0.31443533]
 [0.21113918 0.06050327 0.         0.42911389 0.10130007 0.58870223
  0.48289133 0.49145314 0.46905061 0.26039692]
 [0.62164973 0.48456532 0.42911389 0.         0.39037375 0.63914124
  0.384587   0.60513249 0.33327901 0.35056853]
 [0.30210819 0.12134082 0.10130007 0.39037375 0.         0.49149741
  0.38422456 0.57559113 0.50386151 0.31789625]
 [0.7498206  0.58004839 0.58870223 0.63914124 0.49149741 0.
  0.26675079 1.0602855  0.91470357 0.78385797]
 [0.6851469  0.5023576  0.48289133 0.384587   0.38422456 0.26675079
  0.         0.88783519 0.68903445 0.60216382]
 [0.45874008 0.5270641  0.49145314 0.60513249 0.57559113 1.0602855
  0.88783519 0.         0.31828219 0.28568679]
 [0.56856564 0.5268862  0.46905061 0.33327901 0.50386151 0.91470357
  0.68903445 0.3182821

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

NameError: ignored

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[~(Z[:,0,None]==Z[:,1:]).all(axis=1)]
print(U)

[[2 0 0]
 [0 2 2]
 [2 4 4]
 [4 1 2]
 [4 0 1]
 [0 2 3]
 [4 2 3]
 [3 3 1]
 [2 0 3]
 [3 4 3]]
[[2 0 0]
 [0 2 2]
 [2 4 4]
 [4 1 2]
 [4 0 1]
 [0 2 3]
 [4 2 3]
 [3 3 1]
 [2 0 3]
 [3 4 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[2.62943845e-01, 1.10264316e-01, 5.26769043e-01, 2.94826329e-01,
        1.31154407e-01, 5.34419631e-01, 1.32611895e-01, 1.97678520e-01,
        7.96929814e-03, 4.36571855e-01],
       [1.19990656e-01, 5.03175405e-02, 2.40383505e-01, 1.34539771e-01,
        5.98504343e-02, 2.43874741e-01, 6.05155382e-02, 9.02077600e-02,
        3.63667501e-03, 1.99223310e-01],
       [1.08525555e-01, 4.55097020e-02, 2.17414873e-01, 1.21684502e-01,
        5.41317283e-02, 2.20572522e-01, 5.47332815e-02, 8.15884131e-02,
        3.28919090e-03, 1.80187533e-01],
       [1.18565631e-02, 4.97199628e-03, 2.37528679e-02, 1.32941959e-02,
        5.91396428e-03, 2.40978453e-02, 5.97968478e-03, 8.91364409e-03,
        3.59348539e-04, 1.96857308e-02],
       [1.77536095e-01, 7.44489609e-02, 3.55667268e-01, 1.99062713e-01,
        8.85536655e-02, 3.60832840e-01, 8.95377416e-02, 1.33469838e-01,
        5.38076133e-03, 2.94767357e-01],
       [3.95369092e-01, 1.65796246e-01, 7.92063409e-01, 4.43308410e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.03788849  0.35046576]
